# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Resources\calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTabSet = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabSet.setObjectName("mainTabSet")
        self.isentropicFlowTab = QtWidgets.QWidget()
        self.isentropicFlowTab.setObjectName("isentropicFlowTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.isentropicFlowTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.isentropicFlowTab)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalGroupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.isentropicGammaEntry = QtWidgets.QLineEdit(self.horizontalGroupBox)
        self.isentropicGammaEntry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.isentropicGammaEntry.setObjectName("isentropicGammaEntry")
        self.horizontalLayout.addWidget(self.isentropicGammaEntry)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.horizontalGroupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.isentropicOptionCombo = QtWidgets.QComboBox(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isentropicOptionCombo.sizePolicy().hasHeightForWidth())
        self.isentropicOptionCombo.setSizePolicy(sizePolicy)
        self.isentropicOptionCombo.setMinimumSize(QtCore.QSize(150, 0))
        self.isentropicOptionCombo.setMaximumSize(QtCore.QSize(300, 16777215))
        self.isentropicOptionCombo.setObjectName("isentropicOptionCombo")
        self.horizontalLayout.addWidget(self.isentropicOptionCombo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.isentropicFlowTypeCombo = QtWidgets.QComboBox(self.horizontalGroupBox)
        self.isentropicFlowTypeCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.isentropicFlowTypeCombo.setToolTipDuration(-1)
        self.isentropicFlowTypeCombo.setStatusTip("")
        self.isentropicFlowTypeCombo.setWhatsThis("")
        self.isentropicFlowTypeCombo.setAccessibleName("")
        self.isentropicFlowTypeCombo.setAccessibleDescription("")
        self.isentropicFlowTypeCombo.setObjectName("isentropicFlowTypeCombo")
        self.horizontalLayout.addWidget(self.isentropicFlowTypeCombo)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.isentropicCalcBtn = QtWidgets.QPushButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isentropicCalcBtn.sizePolicy().hasHeightForWidth())
        self.isentropicCalcBtn.setSizePolicy(sizePolicy)
        self.isentropicCalcBtn.setObjectName("isentropicCalcBtn")
        self.horizontalLayout.addWidget(self.isentropicCalcBtn)
        self.horizontalLayout_3.addWidget(self.horizontalGroupBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridGroupBox = QtWidgets.QGroupBox(self.isentropicFlowTab)
        self.gridGroupBox.setTitle("")
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.isentropicT0TEntry = QtWidgets.QLineEdit(self.gridGroupBox)
        self.isentropicT0TEntry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.isentropicT0TEntry.setObjectName("isentropicT0TEntry")
        self.gridLayout.addWidget(self.isentropicT0TEntry, 0, 7, 1, 1)
        self.isentropicP0PEntry = QtWidgets.QLineEdit(self.gridGroupBox)
        self.isentropicP0PEntry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.isentropicP0PEntry.setObjectName("isentropicP0PEntry")
        self.gridLayout.addWidget(self.isentropicP0PEntry, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 5, 1, 1)
        self.isentropicAAStarEntry = QtWidgets.QLineEdit(self.gridGroupBox)
        self.isentropicAAStarEntry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.isentropicAAStarEntry.setObjectName("isentropicAAStarEntry")
        self.gridLayout.addWidget(self.isentropicAAStarEntry, 1, 4, 1, 1)
        self.isentropicRho0RhoEntry = QtWidgets.QLineEdit(self.gridGroupBox)
        self.isentropicRho0RhoEntry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.isentropicRho0RhoEntry.setObjectName("isentropicRho0RhoEntry")
        self.gridLayout.addWidget(self.isentropicRho0RhoEntry, 1, 1, 1, 1)
        self.isentropicMachEntry = QtWidgets.QLineEdit(self.gridGroupBox)
        self.isentropicMachEntry.setMaximumSize(QtCore.QSize(100, 16777215))
        self.isentropicMachEntry.setMaxLength(50)
        self.isentropicMachEntry.setObjectName("isentropicMachEntry")
        self.gridLayout.addWidget(self.isentropicMachEntry, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setTextFormat(QtCore.Qt.RichText)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 6, 1, 1)
        self.horizontalLayout_2.addWidget(self.gridGroupBox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.mainTabSet.addTab(self.isentropicFlowTab, "")
        self.normalShockTab = QtWidgets.QWidget()
        self.normalShockTab.setObjectName("normalShockTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.normalShockTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.normalShockTab)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit = QtWidgets.QLineEdit(self.normalShockTab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.normalShockTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.mainTabSet.addTab(self.normalShockTab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.mainTabSet.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.mainTabSet.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.mainTabSet.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.mainTabSet.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.mainTabSet.addTab(self.tab_7, "")
        self.verticalLayout.addWidget(self.mainTabSet)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainTabSet.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainTabSet.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "Input"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Gamma [γ]:</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Compute From: "))
        self.isentropicFlowTypeCombo.setToolTip(_translate("MainWindow", "<html><head/><body><p>This is used when calculating A/A*</p></body></html>"))
        self.isentropicCalcBtn.setText(_translate("MainWindow", "Calculate"))
        self.label_8.setText(_translate("MainWindow", "Mach:"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>A/A<span style=\" vertical-align:super;\">*</span>:</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>P<span style=\" vertical-align:sub;\">0</span>/P:</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>ρ<span style=\" vertical-align:sub;\">0</span>/ρ:</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>T<span style=\" vertical-align:sub;\">0</span>/T:</p></body></html>"))
        self.mainTabSet.setTabText(self.mainTabSet.indexOf(self.isentropicFlowTab), _translate("MainWindow", "Isentropic"))
        self.normalShockTab.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Gamma [γ]:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.mainTabSet.setTabText(self.mainTabSet.indexOf(self.normalShockTab), _translate("MainWindow", "Normal Shocks"))
        self.mainTabSet.setTabText(self.mainTabSet.indexOf(self.tab_3), _translate("MainWindow", "Oblique Shocks"))
        self.mainTabSet.setTabText(self.mainTabSet.indexOf(self.tab_4), _translate("MainWindow", "Fanno Flow"))
        self.mainTabSet.setTabText(self.mainTabSet.indexOf(self.tab_5), _translate("MainWindow", "Rayleigh Flow"))
        self.mainTabSet.setTabText(self.mainTabSet.indexOf(self.tab_6), _translate("MainWindow", "Prandtl-Meyer"))
        self.mainTabSet.setTabText(self.mainTabSet.indexOf(self.tab_7), _translate("MainWindow", "Rocket Nozzle"))

